# Generated by Django 5.0.3 on 2025-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
